### ISSUE TITLE
Is vert-x3 compatible with java 9?

### ISSUE THREAD

**Issue by PatrickHuetter** [vert-x3/issues#140]
Hi together,

because of some memory leaks which don't get fixed in java 8 but are already fixed in java 9 i need to upgrade my vertx project to run with java 9. I'm using openjdk-8 to compile my project and i'm using openjdk-9-jre (via docker) to run my jar with java 9.

After starting the vertx application with java 9 i get the following message:
`INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.`

Furthermore i get the following exception:

```
SEVERE: Failed in deploying verticle
java.lang.IncompatibleClassChangeError: Method io.vertx.core.Future.future()Lio/vertx/core/Future; must be InterfaceMethodref constant
    at io.vertx.core.Future$future.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
    at DeployVerticle.start(DeployVerticle.groovy:14)
    at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$163(DeploymentManager.java:429)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(java.base@9-internal/Thread.java:843)
```

I already found this issue #116 , but i don't know wether it's already possible to deploy a vertx application on java 9. How is the situation/status?

**Comment by vietj** [comment]
for the former do you have more info ? it seems more like a warning emitted by Netty (and so would be a Netty issue)

for the latter it seems more to be a Groovy issue than a Vert.x issue - can you check that Groovy works with Java 9 ?

**Comment by pmlopes** [comment]
The first one is a netty warning.

**Comment by pmlopes** [comment]
@PatrickHuetter during my non exhaustive java9 tests I can say that you can use JDK9 to **run** your vert.x applications. You will get that warning from Netty so I'd wait until Netty has a proper fix for it before going in production. Also remember that JDK9 is not complete yet so you might encounter blocks that we are not currently testing.

If you also aim for building with Java9 you should be aware that if you use any of the codegen features (say generate polyglot bindings/service proxies) it won't work due to the fact that Java9 is strict with the use of internal APIs. All the remaining core components and hazelcast do seem to work.

Note that i say seem to work, since my tests were purely exploratory but running all the examples in the examples reppo.

**Comment by vietj** [comment]
yes
