### ISSUE TITLE
Aeron integration

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#172]
Aeon is a Java library for efficient reliable UDP unicast, UDP multicast, and IPC message transport: https://github.com/real-logic/Aeron

**Comment by wangbf** [comment]
A udp problem.
I want make a udp server with vertx, so I wrote some code use the official code:
DatagramSocket socket = vertx.createDatagramSocket(new DatagramSocketOptions());
socket.listen(1234, "0.0.0.0", asyncResult -> {
  if (asyncResult.succeeded()) {
    socket.handler(packet -> {
      // Do something with the packet
    });

    // join the multicast group
    socket.listenMulticastGroup("230.0.0.1", asyncResult2 -> {
        System.out.println("Listen succeeded? " + asyncResult2.succeeded());
    });
  } else {
    System.out.println("Listen failed" + asyncResult.cause());
  }
});

when I run it, I had a error in console:
java.lang.NullPointerException: networkInterface
	at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:410)
	at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:369)
	at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:363)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.listenMulticastGroup(DatagramSocketImpl.java:95)
	at com.leim.search.verticle.UDPServiceVerticle2.lambda$start$3(UDPServiceVerticle2.java:22)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$null$0(DatagramSocketImpl.java:205)
	at io.vertx.core.datagram.impl.DatagramChannelFutureListener.notifyHandler(DatagramChannelFutureListener.java:45)
	at io.vertx.core.datagram.impl.DatagramChannelFutureListener.lambda$operationComplete$0(DatagramChannelFutureListener.java:39)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.datagram.impl.DatagramChannelFutureListener.operationComplete(DatagramChannelFutureListener.java:38)
	at io.vertx.core.datagram.impl.DatagramChannelFutureListener.operationComplete(DatagramChannelFutureListener.java:24)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.addListener(DatagramSocketImpl.java:218)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$listen$1(DatagramSocketImpl.java:201)
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:88)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)


It seems like NetworkInterface.getByInetAddress(this.localAddress().getAddress()) make a error, the localAddress is 0.0.0.0, and it can not get a NetworkInterface
