### ISSUE TITLE
After upgrade to 3.3.3 Exceptions thrown when closing vertx

### ISSUE THREAD

**Issue by marcinczeczko** [vert-x3/issues#201]
Hi,
I'm using JUNIT to make integration tests of my app. Up to Vertx 3.3.2 no issues so far. 
What I'm doing in my junit is the helper class being called (let's call it AppHelper) that have static methods to start Vertx and deploy all required verticles together with proper configs.

``` java
@BeforeClass
public static void setUp() throws Exception {
  AppHelper.startApp();
}

@AfterClass
public static void tearDown(TestContext context) {
    AppHelper.teardown(context);
}

public class AppHelper {
  public static Vertx vertx;

  public static void startApp() throws Exception {
      vertx = Vertx.vertx();
      // deploy all required verticles
   }
  public static void tearDown(TestContext context) {
    vertx.close(context.asyncAssertSuccess());
  }
}
```

However, when tearDown() is executed I see following errors on version 3.3.3 (previous versions were fine)

```
2016-10-05 10:38:19 [vert.x-eventloop-thread-2] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
        at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316) ~[vertx-core-3.3.3.jar:na]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
2016-10-05 10:38:19 [vert.x-eventloop-thread-4] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
        at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316) ~[vertx-core-3.3.3.jar:na]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
2016-10-05 10:38:19 [vert.x-eventloop-thread-5] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
        at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340) ~[vertx-core-3.3.3.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316) ~[vertx-core-3.3.3.jar:na]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
```

Could you please guide me what might be wrong, or what I'm might miss ?

BTW. The errors (threads) are related to the verticles that consumes messages on event bus. Other verticles that have httpServer are fine when closing vertx.

**Comment by tsegismont** [comment]
Yes it is a known issue, please read eclipse/vert.x#1625

Only logging should be affected.
