### ISSUE TITLE
Thread blocked in Vertx code enumerating network interfaces

### ISSUE THREAD

**Issue by alasdairg** [vert-x3/issues#232]
Ideally this code should be non-blocking?

io.vertx.core.VertxException: Thread blocked
	at java.net.NetworkInterface.getAll(Native Method)
	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:343)
	at io.netty.util.internal.MacAddressUtil.bestAvailableMac(MacAddressUtil.java:58)
	at io.netty.channel.DefaultChannelId.defaultMachineId(DefaultChannelId.java:127)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:104)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:146)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:114)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:233)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:212)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:348)
	at io.vertx.core.impl.AddressResolver$1.newResolver(AddressResolver.java:167)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:223)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:690)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:74)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:195)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:135)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$start$1(ClusteredEventBus.java:122)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus$$Lambda$19/412773157.handle(Unknown Source)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:271)
	at io.vertx.core.impl.ContextImpl$$Lambda$13/744118510.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$14/576422344.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

**Comment by alexlehm** [comment]
which version of vert.x are you using? I think this was a netty issue that was fixed at some point.

**Comment by alasdairg** [comment]
I believe it's version 3.3.3 ... (Certainly that is the artifact version in
my pom file)

**Comment by alexlehm** [comment]
Sorry, I confused this with another issue.
The code is in a static initializer in the netty code for class DefaultChannelId, I don't think this can be changed on the level of vert.x.

On the plus side, it will only block once since in the initializer code :-)

**Comment by vietj** [comment]
yes, this is rather a netty issue. you should investigate why it is slow and appears as blocking.

**Comment by vietj** [comment]
well netty/jdk :-)

**Comment by JakePi3** [comment]
Seeing this in 3.4.1 when invoking vertx.createHttpServer().listen() 

Same stack trace at the top: 

    at java.net.NetworkInterface.getAll(Native Method)

Taking up to 5 seconds to initialize the first server, then almost no overhead for additional ones after that. This is in a unit test so not sure how this is affecting separation.  When I shut down (vertx.close()) between tests I got a delay each time.
