### ISSUE TITLE
vertx cluster error

### ISSUE THREAD

**Issue by wpxdong** [vert-x3/issues#241]
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder', exception: Failed to load class io.vertx.ext.web.sstore.impl.SessionImpl
	at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
	at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:940)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:94)
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap.lambda$get$0(HazelcastAsyncMap.java:46)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:263)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pmlopes** [comment]
Duplicate: https://github.com/vert-x3/vertx-web/issues/549
