### ISSUE TITLE
vertx ClusteredSession error

### ISSUE THREAD

**Issue by wpxdong** [vert-x3/issues#242]
vertx version:3.4.0  
-------------code-------------
Vertx.clusteredVertx(options, res ->
            {
                if (res.succeeded())
                {
                    Vertx vertx = res.result();
                    runner.accept(vertx);
                }
                else
                {
                    res.cause().printStackTrace();
                }
            });

router.route().handler(SessionHandler.create(ClusteredSessionStore.create(vertx)));
router.route(webContext + "/loginhandler").handler(FormLoginHandler.create(authProvider));

call /loginhandler error
--------------error---------------------
java.lang.NullPointerException
	at io.vertx.ext.web.sstore.impl.SessionImpl.generateId(SessionImpl.java:479)
	at io.vertx.ext.web.sstore.impl.SessionImpl.regenerateId(SessionImpl.java:117)
	at io.vertx.ext.web.handler.impl.FormLoginHandlerImpl.lambda$handle$0(FormLoginHandlerImpl.java:104)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:188)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:324)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vietj** [comment]
should be fixed in 3.4.1 released soon
