### ISSUE TITLE
Simple HttpServer Thread Blocked

### ISSUE THREAD

**Issue by DavidBLWest** [vert-x3/issues#244]
Hi,

I am trying to learn vertx using Mac OSX and having tried both 3.4.0 and 3.4.1 I am stumbling already.

Using either  a TcpServer or HttpServer I get ThreadBlocked exception. For example the code below:

`public class HttpVert1 extends AbstractVerticle {

    @Override
    public void start() {
        System.out.println("HttpVert1 started");

        HttpServer server = vertx.createHttpServer();
        server.requestHandler(handler -> {
            System.out.println("Handled");
        });
        server.listen(8080);

    }

    @Override
    public  void stop() {
        System.out.println("HttpVert1 stopped");
    }
}`

With this I get the following:

HttpVert1 started
Mar 16, 2017 12:44:11 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2434 ms, time limit is 2000
Mar 16, 2017 12:44:12 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3436 ms, time limit is 2000
Mar 16, 2017 12:44:13 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4436 ms, time limit is 2000
Mar 16, 2017 12:44:14 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5439 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	at sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:140)
	at sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:121)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:78)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:147)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:235)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:249)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:347)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:153)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:84)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:73)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:157)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:83)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:711)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:74)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:294)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:224)
	at com.lbbw.vertx.web.servers.HttpVert1.start(HttpVert1.java:21)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.DeploymentManager$$Lambda$7/1796488937.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl$$Lambda$8/1740035246.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

I would really appreciate some help on understanding why with a very simple setup I am getting this problem.

Thank you very much!

**Comment by tsegismont** [comment]
You're probably hitting this https://thoeni.io/post/macos-sierra-java/



2017-03-16 13:52 GMT+01:00 DavidOumamar <notifications@github.com>:

**Comment by DavidBLWest** [comment]
That was it, thank you so much!!!
