### ISSUE TITLE
Failed to create a new channel from an accepted socket.

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#271]
I've built a web service with Vert.x that listens on 40 ports.
It works fine most of the time but at some condition which I cannot reproduce I get this start getting this exception (in production)
```
2017-06-07 09:52:26.435  WARN 23101 --- [ceptor-thread-0] i.n.c.socket.nio.NioServerSocketChannel  : Failed to create a new channel from an accepted socket.

java.lang.NoClassDefFoundError: Could not initialize class sun.nio.ch.SocketChannelImpl$DefaultOptionsHolder
        at sun.nio.ch.SocketChannelImpl.supportedOptions(SocketChannelImpl.java:251)
        at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:169)
        at sun.nio.ch.SocketAdaptor.setBooleanOption(SocketAdaptor.java:271)
        at sun.nio.ch.SocketAdaptor.setTcpNoDelay(SocketAdaptor.java:306)
        at io.netty.channel.socket.DefaultSocketChannelConfig.setTcpNoDelay(DefaultSocketChannelConfig.java:255)
        at io.netty.channel.socket.DefaultSocketChannelConfig.<init>(DefaultSocketChannelConfig.java:55)
        at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.<init>(NioSocketChannel.java:481)
        at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.<init>(NioSocketChannel.java:479)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:99)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:145)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:433)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
```
Upon every request.

the HTTP server is very simple, it just returns a static json on every POST request.
I could not reproduce it on my laptop and there's nothing special in the environment that I can think of.
Any idea of what maybe the issue?
Thanks

**Comment by vietj** [comment]
it does not seem to be a Vert.x or Netty issue, other users have reported this issue that might be related to native libraries, https://stackoverflow.com/questions/32293736/why-would-socketchannelimpldefaultoptionsholder-not-be-found

**Comment by michaelpog** [comment]
I'm not using any native library, I'm just using vertx, I have 2 verticles that just listen on ports and that's it.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by michaelpog** [comment]
I cannot, that's the problem. All I notice is that I launch it, then leave it running for a day or two, and then suddenly I realize that all my requests time out, and when I look at the logs that's what I see.
Also looking at the stack trace it is in netty

**Comment by vietj** [comment]
this seems to be a JVM issue to me

**Comment by michaelpog** [comment]
I will run with  remote debugging flags and when it happens I'll attach and see what exactly is happening. I'll update as soon as I get the info

**Comment by vietj** [comment]
thanks

**Comment by michaelpog** [comment]
@vietj update on this problem.
I have been running the vertx based webserver with an open port for remote debugging. When the application became unresponsive, I attached the debugger, and I see that the acceptor thread disappeared as if it crashed at some point.  I do not see any error log message though.
How can I debug this issue? I think this is hitting some bug/edge case

**Comment by vietj** [comment]
can you set an uncaught exception handler to related the acceptor handler thread crash ?  something like:

```
    ((VertxInternal)vertx).getAcceptorEventLoopGroup().next().execute(() -> {
      Thread.currentThread().setUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
        @Override
        public void uncaughtException(Thread t, Throwable e) {

        }
      });
    });
```

**Comment by michaelpog** [comment]
Ok I set a break point and this is what I see in the variables 
```
t = {VertxThread@3886} "Thread[vert.x-acceptor-thread-0,5,main]"
 worker = false
 maxExecTime = 2000000000
 execStart = 0
 context = null
 threadLocalMap = {InternalThreadLocalMap@4243} 
 name = "vert.x-acceptor-thread-0"
 priority = 5
 threadQ = null
 eetop = 140408947994624
 single_step = false
 daemon = false
 stillborn = false
 target = {SingleThreadEventExecutor$5@4245} 
 group = {ThreadGroup@3901} "java.lang.ThreadGroup[name=main,maxpri=10]"
 contextClassLoader = {LaunchedURLClassLoader@3885} 
 inheritedAccessControlContext = {AccessControlContext@4246} 
 threadLocals = {ThreadLocal$ThreadLocalMap@4247} 
 inheritableThreadLocals = {ThreadLocal$ThreadLocalMap@4248} 
 stackSize = 0
 nativeParkEventPointer = 0
 tid = 27
 threadStatus = 5
 parkBlocker = null
 blocker = null
 blockerLock = {Object@4249} 
 uncaughtExceptionHandler = {VerticlesDeployer$1@4220} 
 threadLocalRandomSeed = 0
 threadLocalRandomProbe = 0
 threadLocalRandomSecondarySeed = 0
e = {NoClassDefFoundError@4221} "java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy"
 detailMessage = "ch/qos/logback/classic/spi/ThrowableProxy"
  value = {char[41]@4239} 
  hash = 0
 cause = {NoClassDefFoundError@4221} "java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy"
  detailMessage = "ch/qos/logback/classic/spi/ThrowableProxy"
  cause = {NoClassDefFoundError@4221} "java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy"
  stackTrace = {StackTraceElement[0]@4230} 
  suppressedExceptions = {Collections$UnmodifiableRandomAccessList@4231}  size = 0
 stackTrace = {StackTraceElement[0]@4230} 
```


So in short the exception is ```java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy```
And no stack trace

**Comment by vietj** [comment]
are you using logback logger ?

**Comment by vietj** [comment]
you don't have stack trace yet because the stack trace has not been initialized, can you try to log the stack trace with err.printStackTrace() ?

**Comment by michaelpog** [comment]
Looks like this is the stack trace 
```
java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.warn(Logger.java:713)
	at io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:861)
	at java.lang.Thread.run(Thread.java:745)

2017-10-25 11:49:47.641 ERROR 25842 --- [ntloop-thread-3] io.vertx.core.impl.ContextImpl           : Unhandled exception

java.lang.NoClassDefFoundError: io/vertx/ext/web/impl/HeaderParser
        at io.vertx.ext.web.impl.RoutingContextImpl.fillParsedHeaders(RoutingContextImpl.java:82)
        at io.vertx.ext.web.impl.RoutingContextImpl.<init>(RoutingContextImpl.java:64)
        at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
        at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:285)
        at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:429)
        at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:763)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:757)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:621)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:573)
        at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1064)
        at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:1035)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.vertx.ext.web.impl.HeaderParser
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 40 common frames omitted

```
I am using logback.
It's a spring boot application, I have a logback.xml in its classpath that looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <logger name="org.apache.http.headers" level="INFO"/>
</configuration>
``` (very generic one) and in fact logback logging works just fine.

Looks like it happens when I start it and immediately send a lot of requests to the server.

When I attached the debugger I also saw the java.io.IOException: Too many open files in the acceptor threads.

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by michaelpog** [comment]
Yes, will be ready in a few minutes.

**Comment by michaelpog** [comment]
https://github.com/michaelpog/vert.x-webserver

**Comment by michaelpog** [comment]
@vietj were you able to reproduce? Any thoughts on this?

**Comment by vietj** [comment]
not yet,sorry

**Comment by michaelpog** [comment]
Please let me know if I can do anything to debug on my end. 
I'm about to migrate a major application to Vert.x in production and I'm really having concerns about this error.
I really appreciate you looking into it.

**Comment by michaelpog** [comment]
@vietj  I was not able to reproduce this in a while. If I do I can create a new issue. Feel free to close this if you'd like
