### ISSUE TITLE
vertx-mongo: Max number of operations (maxWaitQueueSize) of 500 has been exceeded.

### ISSUE THREAD

**Issue by gillbates** [vert-x3/issues#287]
Hi all,

during the development with mongo and vertx, we happened to meet a problem by failed setting the value of maxWaitQueueSize.
i.e, it seemed the vertx-mongo hasnot utilize the pooling for the connections to mongo, which is implemented in the official mongo java driver.

```
JsonObject config = new JsonObject();
config.put("host", "127.0.0.1").put("port", 27017).put("db_name", "btc").put("waitQueueMultiple", 10000);

```
Using the following code with mongo default setup, the vertx-mongo will throw 

```
com.mongodb.MongoWaitQueueFullException: Too many operations are already waiting for a server. Max number of operations (maxWaitQueueSize) of 500 has been exceeded.
	at com.mongodb.connection.BaseCluster.createWaitQueueFullException(BaseCluster.java:384)
	at com.mongodb.connection.BaseCluster.notifyWaitQueueHandler(BaseCluster.java:431)
	at com.mongodb.connection.BaseCluster.selectServerAsync(BaseCluster.java:142)
	at com.mongodb.binding.AsyncClusterBinding.getAsyncClusterBindingConnectionSource(AsyncClusterBinding.java:75)
	at com.mongodb.binding.AsyncClusterBinding.getReadConnectionSource(AsyncClusterBinding.java:65)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:446)
	at com.mongodb.operation.FindOperation.executeAsync(FindOperation.java:546)
	at com.mongodb.async.client.MongoClientImpl$2.execute(MongoClientImpl.java:123)
	at com.mongodb.async.client.OperationIterable.batchCursor(OperationIterable.java:132)
	at com.mongodb.async.client.OperationIterable.into(OperationIterable.java:64)
	at com.mongodb.async.client.FindIterableImpl.into(FindIterableImpl.java:169)
	at io.vertx.ext.mongo.impl.MongoClientImpl.findWithOptions(MongoClientImpl.java:267)
	at io.vertx.ext.mongo.impl.MongoClientImpl.find(MongoClientImpl.java:249)
	at com.xxx.play.test.MongoWaitQueueFull.main(MongoWaitQueueFull.java:20)
```

 we've attached a sample code to reproduce the issue, anyone may have a look or having the same issue?

sample code:

```
public class MongoWaitQueueFull {
    public static void main(String[] args) {
        JsonObject config = new JsonObject();
        config.put("host", "127.0.0.1").put("port", 27017).put("db_name", "btc").put("waitQueueMultiple", 10000);
        Vertx vertx = Vertx.vertx();
        MongoClient mongoClient = MongoClient.createShared(vertx, config);
        for (int i = 0; i < 1000; i++) {
            Future<List<JsonObject>> future = Future.future();
            mongoClient.find("tick", new JsonObject(), future.completer());
            future.setHandler(r -> {
                if (r.succeeded()) {
                    System.out.println("find success");
                } else {
                    System.out.println(r.cause());
                }
            });
        }
        vertx.setTimer(100000, l -> System.out.println("close"));
    }
}
```

**Comment by karianna** [comment]
See https://github.com/vert-x3/vertx-mongo-client/pull/98 as a semi related issue.  Can you open this as an issue over at https://github.com/vert-x3/vertx-mongo-client/ and we'll take a look
