### ISSUE TITLE
ClassCastException for Http2pool

### ISSUE THREAD

**Issue by dankristensen** [vert-x3/issues#291]
I get this Exception:

ERROR 2017-08-30 15:28:25,492 [vert.x-eventloop-thread-9] - : io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.ClassCastException: io.vertx.core.http.impl.Http2Pool cannot be cast to io.vertx.core.http.impl.Http1xPool
at io.vertx.core.http.impl.ConnectionManager$ConnQueue.lambda$http1xConnected$1(ConnectionManager.java:352)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
at io.vertx.core.http.impl.ConnectionManager$ConnQueue.http1xConnected(ConnectionManager.java:351)
at io.vertx.core.http.impl.ConnectionManager$ConnQueue.access$1500(ConnectionManager.java:197)
at io.vertx.core.http.impl.ConnectionManager$ChannelConnector.lambda$null$1(ConnectionManager.java:529)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1324)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1172)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:748)

I have looked at the code, but cannot found a reason for this.

This is a snippet showing how i instantiate the HttpClient:

```
        final HttpClientOptions httpClientOptions = new HttpClientOptions();
        if (port.intValue() == 443) {
            httpClientOptions
                    .setSsl(true)
                    .setProtocolVersion(HttpVersion.HTTP_2)
                    .setTrustAll(true);
        }
        HttpClient httpClient = vertx.createHttpClient(httpClientOptions);

```

I am using vert.x 3.4.2 for this.
Any Clues?

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by vietj** [comment]
does it happen with a particular server ?

**Comment by dankristensen** [comment]
I have 4 different verticle's, which all has their own HttpClient.

One of these are using ssl and only communicating over HTTP/2

Are the HttpClient's using the same Connection pool underneath, and mixing these somehow?

**Comment by vietj** [comment]
@dankristensen no the pool is per client. It could be a bug in HttpClient, that's why I would like to have  a reproducer

**Comment by vietj** [comment]
it happens that the pool can change, i.e you ask for an HTTP/2 connection but ALPN negotiates to HTTP/1.1 or ALPN is not supported on the server, then the pool becomes an HTTP/1.1 pool, so there may be a bug there.

**Comment by dankristensen** [comment]
In the code marked here from master:

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L522-L534

It looks like that if i am running ssl, it will always use a http1connection, if i am NOT using alpn. 

Is this correct. Can i not use http/2 without ALPN?

**Comment by vietj** [comment]
yes you cannot (per the spec), perhaps this should be checked in the options.

**Comment by vietj** [comment]
From RFC : 

```implementations that support HTTP/2 over TLS MUST use protocol negotiation in TLS [TLS-ALPN].```

**Comment by dankristensen** [comment]
Thanx a lot for helping clarify this. I believe it should be checked, so others don't make the same mistake as me.

**Comment by dankristensen** [comment]
You may close this issue, unless you want it to track the check in HttpClientOptions.

**Comment by vietj** [comment]
I think it should be checked in the options and fails explicitly when it happens

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/issues/2109

**Comment by vietj** [comment]
closing this one

**Comment by vietj** [comment]
thanks for investigating the issue in the source code
