### ISSUE TITLE
After used, NetSocket must close??

### ISSUE THREAD

**Issue by laudylcp** [vert-x3/issues#326]
2018-01-24 13:14:01.221 [vert.x-eventloop-thread-2] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_152]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_152]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_152]
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[obdpps-0.0.1-fat.jar:?]
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[obdpps-0.0.1-fat.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[obdpps-0.0.1-fat.jar:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141) ~[obdpps-0.0.1-fat.jar:?]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [obdpps-0.0.1-fat.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [obdpps-0.0.1-fat.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [obdpps-0.0.1-fat.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [obdpps-0.0.1-fat.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [obdpps-0.0.1-fat.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [obdpps-0.0.1-fat.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

My TCP Server and connection handler is below:

![default](https://user-images.githubusercontent.com/23287431/35318761-c80d373c-0117-11e8-8e6c-77ced44bf2d7.png)

Because I want a long connection, so after used, the NetSocket is not close.

After used, NetSocket must close??

Thanks for your help!!!

**Comment by tsegismont** [comment]
@laudylcp it's fine to keep long-lived TCP connections. But the OS has a limit on the number of opened file descriptors. It seems you reached yours. Google "too many open files" for your system and you will find how to increase that limit.

**Comment by vietj** [comment]
@laudylcp it's your responsibility to close net sockets according to your protocol
