### ISSUE TITLE
EventBus.send with large sendTimeout gets ignored?

### ISSUE THREAD

**Issue by MrTetrixx** [vert-x3/issues#327]
I ran across an issue with sendTimeout on EventBus.send().
If a very large sendTimeout is used it seems to be treated as no timeout and fails immediately.
I am using vertx 3.5.0. I saw this in more realistic code than the example code below but it seems to replicate it:

```java
public static void main(String[] args) {
        final String address = "address";
        Vertx vertx = Vertx.vertx();
        DeliveryOptions options = new DeliveryOptions()
                .setSendTimeout(Long.MAX_VALUE);

        vertx.eventBus().consumer(address, r -> {
            r.reply("thanks");
            System.out.println("got it: " + r.body());
        });

        Future<Void> f = Future.future();
        vertx.eventBus().send(address, "ahoy there!", options, result -> {
            if (result.failed()) {
                System.out.println("no response after " + Duration.ofMillis(Long.MAX_VALUE).toDaysPart() + " days");
                f.fail(result.cause());
            } else {
                f.complete();
                System.out.println("got a response: " + result.result());
            }
        });
        f.setHandler(r -> vertx.close());
    }
```
Running the above code immediately returns:
```
no response after 106751991167 days
```

**Comment by vietj** [comment]
this is because you are using an unrealistic timeout value that gets translated into a negative clock (overflow)  time, a more correct value would be:

```
long maxValue = Long.MAX_VALUE / TimeUnit.MILLISECONDS.toNanos(1) - System.currentTimeMillis();
```

but that an invalid timeout value by the JVM when Netty polls the selector:

```
java.io.IOException: Invalid argument
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
as the method is native, I don't know (yet) what would be the max value you can use...

what is your actual use case to set such kind of infinite timer ?

in this situation you should rather use the event bus differently and set a reply address yourself instead of using the request/reply paradigm.

**Comment by MrTetrixx** [comment]
Yes, I know its a rather silly problem, Long.MAX_VALUE is rather silly.
But the signature of `sendTimeout` is a long and it goes all the way to its maximum value. I really like vertx and was a bit surprised that it acted a bit strange. If the long is too big maybe use something smaller or reject illegal ranges.

**Comment by vietj** [comment]
yes we should do that, however the main issue here is that the selector upper bound rejection is not known and not explained in the javadoc of the method

**Comment by vietj** [comment]
also netty should do a check (AbstractScheduledEventExecutor) : 

```
    @Override
    public ScheduledFuture<?> schedule(Runnable command, long delay, TimeUnit unit) {
        ObjectUtil.checkNotNull(command, "command");
        ObjectUtil.checkNotNull(unit, "unit");
        if (delay < 0) {
            delay = 0;
        }
        return schedule(new ScheduledFutureTask<Void>(
                this, command, null, ScheduledFutureTask.deadlineNanos(unit.toNanos(delay))));
    }
```

the call to `ScheduledFutureTask.deadlineNanos(unit.toNanos(delay))` generates a negative value.

**Comment by vietj** [comment]
perhaps we should have a max fixed value in Vert.x (like 10 days ?)

**Comment by vietj** [comment]
10 days is unrealistic, specially if you send many messages regularly you may OOM due to the accumulation of timers and in this case request/response is not what you arel ooking for

**Comment by vietj** [comment]
in this case you would rather have a shared address to reply to, that you send to in the request message and have all the contextual data part of the message
