### ISSUE TITLE
二月 24, 2018 10:39:22 上午 io.vertx.core.eventbus.impl.clustered.ConnectionHolder 警告: Connecting to server localhost:4857 failed io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:4857

### ISSUE THREAD

**Issue by felix-laofan** [vert-x3/issues#332]
二月 24, 2018 10:39:22 上午 io.vertx.core.eventbus.impl.clustered.ConnectionHolder
警告: Connecting to server localhost:4857 failed
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:4857
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 more

when in different pc error.
source
	Config config = new ClasspathXmlConfig("xmlconfig/simple-config.xml");
		ClusterManager mgr = new HazelcastClusterManager(config);
		VertxOptions options = new VertxOptions().setClusterManager(mgr);
		Vertx.clusteredVertx(options, res -> {
		  if (res.succeeded()) {
			System.out.println("ffffffffffffff");
		    Vertx vertx = res.result();
			vertx.eventBus().send("testMsg", "laofan send::"+new Date().toGMTString());
//		    vertx.setPeriodic(1000, id->{
////		    	vertx.eventBus().registerCodec(codec);
//		    	vertx.eventBus().send("testMsg", "laofan send::"+new Date().toGMTString());
//		    	vertx.eventBus().send("testMsg1", "laofan send::"+new Date().toGMTString());
//		    });
		  } else {
		    
		  }
		});

**Comment by tsegismont** [comment]
@felix-laofan please use shorter issue sensible issue titles.

If you don't use the CLI or a fat-JAR with the `Launcher` main class, you must set the cluster host name with `io.vertx.core.VertxOptions#setClusterHost`. Otherwise it defaults to `localhost`

**Comment by willks** [comment]
@tsegismont Thanks for this. I was debugging this for 5 hours on Kubernetes cluster, and one of our devs removed the "setClusterHost" and everything was going to localhost. The dev did it to make it work on local environment... but ******** up our UAT clustered bus!
