### ISSUE TITLE
refresh a file upload request in firefox cause vertx to print exception forever

### ISSUE THREAD

**Issue by kobe2000** [vert-x3/issues#344]
I wrote a simple html for file uploading:
```html
<form method="post" enctype="multipart/form-data" action="http://localhost/" target="result">
    <label>img:<input type="file" name="image"></label><br>
    <input type="submit">
</form>
```
and a simple embed http server:
```kotlin
class SimpleServer {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            val vertx = Vertx.vertx()
            val server = vertx.createHttpServer()
            server.requestHandler { request ->
                request.response().end("hello")
            }.listen()
        }
    }
}
```
The first time to submit the file upload form, everything is ok, but if I refresh the result page(F5) one exception will be printed infinitly:
```java
10:03:13.841 [vert.x-eventloop-thread-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: text is empty (possibly HTTP/0.9)
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:63)
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Vertx version is 3.5.1
Firefox version is 59.0.1(Closing Firefox didn't stop the exception from printing)
IE is OK.

I can not figure it out, please help
Thanks

**Comment by tsegismont** [comment]
Nice catch. I was able to reproduce. We will take a look.

**Comment by mitjabez** [comment]
https://github.com/eclipse/vert.x/issues/2380 fixes this issue.

**Comment by tsegismont** [comment]
@kobe2000 looked into this again. I still can reproduce with Firefox 59.0.2. But when I tried with Chrome, it works fine. Which browser did you try? Can you try with another browser? Thanks

**Comment by tsegismont** [comment]
@kobe2000 nevermind, I didn't notice the last part of your comments

**Comment by tsegismont** [comment]
@chili1k I'm not sure eclipse/vert.x#2375 removes the exception in logs. But in master, it's definitely gone.

@kobe2000 @chili1k there's still definitely a bug in Firefox. Would be nice to report it

**Comment by tsegismont** [comment]
Closing as fixed in master and happens only when refreshing Firefox after a POST request
