### ISSUE TITLE
Write to secure websocket using proxy server fails with UnsupportedMessageTypeException

### ISSUE THREAD

**Issue by spn** [vert-x3/issues#348]
As of vert.x 3.5.1, connecting to secure websocket server using a proxy doesn't work.
After handshake, any attempt to send a websocket frame fails with:
```
io.netty.handler.codec.UnsupportedMessageTypeException: io.netty.handler.codec.http.websocketx.BinaryWebSocketFrame (expected: io.netty.buffer.ByteBuf)
	at io.netty.handler.ssl.SslHandler.write(SslHandler.java:711)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.write(CombinedChannelDuplexHandler.java:528)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:101)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:95)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:105)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:122)
	at io.vertx.core.http.impl.WebSocketImplBase.writeFrame(WebSocketImplBase.java:252)
	at io.vertx.core.http.impl.WebSocketImplBase.writePartialMessage(WebSocketImplBase.java:229)
	at io.vertx.core.http.impl.WebSocketImplBase.writeMessageInternal(WebSocketImplBase.java:200)
	at io.vertx.core.http.impl.WebSocketImplBase.writeBinaryMessage(WebSocketImplBase.java:163)
	at io.vertx.core.http.impl.WebSocketImpl.writeBinaryMessage(WebSocketImpl.java:27)
```

The error itself is not visible (websocket just silently disconnects), I got the above stacktrace trying to debug the problem.

I'm still not sure if it's a vert.x or Netty issue (looking at https://github.com/netty/netty/issues/5201). Running without a proxy works fine.

**Comment by vietj** [comment]
can you create a test for reproducing the case ?

**Comment by spn** [comment]
This one works for me.
When proxy is disabled, this works and implements simple echo test.
When proxy enabled, will fail with `UnsupportedMessageTypeException`.

The test is using locally-installed `tinyproxy` which is a proxy server supporting `CONNECT`.

```
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.http.WebSocket;
import io.vertx.core.http.WebsocketVersion;
import io.vertx.core.net.ProxyOptions;

public class WebsocketProxyTest {

    public static void main(String[] args) {
        final String hello = "Hello!";
        Vertx vertx = Vertx.vertx();
        HttpClientOptions options = new HttpClientOptions();
        options.setConnectTimeout(2000);
        options.setVerifyHost(false);
        ProxyOptions proxy = new ProxyOptions();
        proxy.setHost("127.0.0.1");
        proxy.setPort(8888);
        options.setProxyOptions(proxy);
        options.setSsl(true);
        try {
            final HttpClient client = vertx.createHttpClient(options);
            HttpClient ws = client.websocket(443, "echo.websocket.org", "/", null, WebsocketVersion.V13, (WebSocket websocket) -> {
                websocket.frameHandler((frame) -> {
                    if (frame.isText()) {
                        System.out.println("<= " + frame.textData());
                        websocket.close();
                    }
                });
                System.out.println("Connected.");
                vertx.setTimer(1000, (timerId) -> {
                    websocket.writeTextMessage(hello);
                    System.out.println("=> " + hello);
                });
                websocket.closeHandler((v) -> {
                    System.out.println("Websocket closed.");
                    System.exit(0);
                });
            });

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
