### ISSUE TITLE
vertx3 grpc cant work native transport

### ISSUE THREAD

**Issue by AllenRay** [vert-x3/issues#361]
i have set vertx option  preferNativeTransport to true but deploy grpc VertxServer failed. 
The stack as below
 java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:206)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:151)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:75)
	at io.vertx.grpc.VertxServer$ActualServer.lambda$null$1(VertxServer.java:88)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.nio.NioEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:469)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:331)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278)
	at io.grpc.netty.NettyServer.start(NettyServer.java:198)
	... 9 common frames omitted

. i think root cause is hard code set workerEventLoopGroup to VertxEventLoopGroup in VertxServer line 73.  should use different event loop by different platform.
any question please contact me
thanks.

**Comment by vietj** [comment]
@AllenRay can you provide a project that reproduces this ?

**Comment by jo5ef** [comment]
The following test reproduces this issue:

```
@RunWith(VertxUnitRunner.class)
public class NativeTransportTest {
  @Test
  public void test(TestContext ctx) {
    Vertx vertx = Vertx.vertx(new VertxOptions().setPreferNativeTransport(true));
    VertxServerBuilder.forPort(vertx, 0)
      .addService(new GreeterGrpc.GreeterImplBase() { })
      .build()
      .start(ctx.asyncAssertSuccess());
  }
}
```
This test uses the Greeter proto from the vertx-grpc tests (add the native dependencies to the pom if you run it there).

**Comment by vietj** [comment]
do you know if netty-grpc can support native transport, i.e can it use a native event loop and bootstrap ?

**Comment by jo5ef** [comment]
Yes, grpc-java supports native netty event loops but doesn't detect them automatically ([grpc-java issue 3473](https://github.com/grpc/grpc-java/issues/3473)). But the ELG can be passed to the `NettyServerBuilder`. I've done that in [this PR](https://github.com/vert-x3/vertx-grpc/pull/30) and it works.
