### ISSUE TITLE
Deadlock can occur with some methods are called from the worker thread

### ISSUE THREAD

**Issue by luengnat** [vert-x3/issues#364]
This can actually block forever sometimes. I haven't dug down what happened.
```
"vert.x-worker-thread-2" #209 prio=5 os_prio=0 tid=0x00007f212801a000 nid=0x316 waiting for monitor entry [0x00007f20b06c9000]
java.lang.Thread.State: BLOCKED (on object monitor)
at io.vertx.core.http.impl.HttpServerRequestImpl.isEnded(HttpServerRequestImpl.java:348)
- waiting to lock <0x000000070437c000> (a io.vertx.core.http.impl.ServerConnection)
at io.vertx.ext.web.impl.HttpServerRequestWrapper.isEnded(HttpServerRequestWrapper.java:226)
...
at io.vertx.ext.web.impl.RouteImpl.handleFailure(RouteImpl.java:223)
- locked <0x00000006c5bfd300> (a io.vertx.ext.web.impl.RouteImpl)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:76)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:420)
at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:151)
...
at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:739)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
....
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:751)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
```

**Comment by vietj** [comment]
can you should the other thread deadlocking with this one ?

**Comment by luengnat** [comment]
The eventloop thread locks on Connection and then tries to lock on Router while FailureHandler locks on Router and then tries to lock on Connection.

```
io.vertx.ext.web.impl.RouteImpl.matches(RoutingContext, String, boolean) RouteImpl.java:229
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext() RoutingContextImplBase.java:70
io.vertx.ext.web.impl.RoutingContextImpl.next() RoutingContextImpl.java:118
...
io.vertx.ext.web.impl.RouteImpl.handleContext(RoutingContext) RouteImpl.java:217
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext() RoutingContextImplBase.java:78
io.vertx.ext.web.impl.RoutingContextImpl.next() RoutingContextImpl.java:118
...
io.vertx.ext.web.impl.RouteImpl.handleContext(RoutingContext) RouteImpl.java:217
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext() RoutingContextImplBase.java:78
io.vertx.ext.web.impl.RoutingContextImpl.next() RoutingContextImpl.java:118
...
io.vertx.ext.web.impl.RouteImpl.handleContext(RoutingContext) RouteImpl.java:217
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext() RoutingContextImplBase.java:78
io.vertx.ext.web.impl.RoutingContextImpl.next() RoutingContextImpl.java:118
...
io.vertx.ext.web.impl.RouteImpl.handleContext(RoutingContext) RouteImpl.java:217
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext() RoutingContextImplBase.java:78
io.vertx.ext.web.impl.RoutingContextImpl.next() RoutingContextImpl.java:118
io.vertx.ext.web.impl.RouterImpl.accept(HttpServerRequest) RouterImpl.java:79
...
io.vertx.core.http.impl.ServerConnection.handleRequest(HttpServerRequestImpl, HttpServerResponseImpl) ServerConnection.java:285
io.vertx.core.http.impl.ServerConnection.processMessage(Object) ServerConnection.java:429
io.vertx.core.http.impl.ServerConnection.handleMessage(Object) ServerConnection.java:131
io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(ServerConnection, ChannelHandlerContext, Object) HttpServerImpl.java:630
io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(ConnectionBase, ChannelHandlerContext, Object) HttpServerImpl.java:580
io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(ConnectionBase, ChannelHandlerContext, Object) VertxHttpHandler.java:71
io.vertx.core.http.impl.VertxHttpHandler$$Lambda$383.run()
io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(boolean, PoolMetrics, Object, ContextTask, Handler) ContextImpl.java:335
io.vertx.core.impl.ContextImpl$$Lambda$152.run()
io.vertx.core.impl.ContextImpl.executeFromIO(ContextTask) ContextImpl.java:193
io.vertx.core.http.impl.VertxHttpHandler.channelRead(ConnectionBase, ContextImpl, ChannelHandlerContext, Object) VertxHttpHandler.java:71
io.vertx.core.net.impl.VertxHandler.channelRead(ChannelHandlerContext, Object) VertxHandler.java:122
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:363
```

**Comment by vietj** [comment]
I can't see the lock here, can you provide info about the exact deadlock info of the two threads ? also a reproducer would be great

**Comment by luengnat** [comment]
the deadlock is pretty clear here. Basically, 
`io.vertx.core.http.impl.ServerConnection.handleMessage(Object) ServerConnection.java:131` takes a lock on `Connection` first and `io.vertx.ext.web.impl.RouteImpl.matches` takes a lock on `Route` second

while the event loop thread takes a lock in another order where `io.vertx.ext.web.impl.RouteImpl.handleFailure` takes a lock on `Route`  and then `io.vertx.core.http.impl.HttpServerRequestImpl.isEnded` takes a lock `Connection`.

That's how you end up with deadlock.

**Comment by luengnat** [comment]
The general theme here happens in many code paths of Vert.x where `synchronized` block is used for thread synchronization. However, when starting to use across threads, it will be prone to deadlock as there are multiple locks being used.

**Comment by vietj** [comment]
I would like to see side by side the two stack trace entirely of the deadlock thanks

**Comment by pmlopes** [comment]
Matching is now lock free.

**Comment by sliechti-ib** [comment]
@pmlopes  after what release is the matching lock free?
Currently experiencing it on 3.2.1

`Name[vert.x-eventloop-thread-2]Thread ID[49] Deadlocked on Lock[io.vertx.ext.web.impl.RouteImpl@cb2189f] held by thread [vert.x-eventloop-thread-5] Thread ID[52] Thread stack [
io.vertx.ext.web.impl.RouteImpl.matches(RouteImpl.java:233)
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:70)
io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:94)
io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:144)
`
