### ISSUE TITLE
java.io.IOException in Vert.x 3.5.2-SNAPSHOT

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#368]
I've been experimenting with this version recently, and I see the following exception in the logs:
```
2018-05-09 15:59:01.522-0700 vert.x-eventloop-thread-0 ERROR Unhandled exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

I am still not sure why this is happening.
But I see about 20/30 of them per minute.

Looking at another view in Java Mission Control
I see actually two places for the IOException:

One stack trace:
```
Stack Trace	Count
java.lang.Throwable.<init>(String)	55
   java.lang.Exception.<init>(String)	55
      java.io.IOException.<init>(String)	55
         sun.nio.ch.FileDispatcherImpl.read0(FileDescriptor, long, int)	29
            sun.nio.ch.SocketDispatcher.read(FileDescriptor, long, int)	29
               sun.nio.ch.IOUtil.readIntoNativeBuffer(FileDescriptor, ByteBuffer, long, NativeDispatcher)	29
                  sun.nio.ch.IOUtil.read(FileDescriptor, ByteBuffer, long, NativeDispatcher)	29
                     sun.nio.ch.SocketChannelImpl.read(ByteBuffer)	29
                        io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(int, ScatteringByteChannel, int)	29
                           io.netty.buffer.AbstractByteBuf.writeBytes(ScatteringByteChannel, int)	29
                              io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(ByteBuf)	29
                                 io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read()	29
                                    io.netty.channel.nio.NioEventLoop.processSelectedKey(SelectionKey, AbstractNioChannel)	29
                                       io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized()	29
                                          io.netty.channel.nio.NioEventLoop.processSelectedKeys()	29
                                             io.netty.channel.nio.NioEventLoop.run()	29
                                                io.netty.util.concurrent.SingleThreadEventExecutor$5.run()	29
                                                   io.netty.util.concurrent.FastThreadLocalRunnable.run()	29
                                                      java.lang.Thread.run()	29

```

Unfortunately that's all the details I have

**Comment by manish-panwar** [comment]
I assume you are using Vertx HTTP/Web client API to talk to remote server. It means you are receiving RST from remote - and I doubt that Vertx can do much here. Were you not seeing it in older version of Vertx?

**Comment by michaelpog** [comment]
Yes.
I am using an HTTP Web client.
I have no see this error before. I've had Vert.x 3.5.0 in production for a few weeks and I have not seen this error there.

**Comment by manish-panwar** [comment]
Prod environment network/service/firwall/etc might be setup differently than your Dev env (you said you are experimenting). Lets see what @vietj and teams says, but if I was you, I would try to deploy older version of Vertx in your Dev environment and see if you are able to reproduce. Stacktrace you posted above won't really help much. Also, another thing I would have tried is to point my WebClient to some open API on Internet and if you see same issue - I am wondering if something wrong with your remote service.

Reason I am saying this, I have seen these errors all the time in our environment, and error percentage depends on service you are hitting or environment you are in. e..g in my load test environment I never see this error, but in Prod I see this error regardless of Vertx version. Vertx wouldn't know who & why has returned RST TCP status.

**Comment by michaelpog** [comment]
@manish-panwar I've testing 3.5.0 in production and I did not see that issue.
I'm waiting for 3.5.2 to come out so I wanted to test the SNAPSHOT version. Every time I tried the 3.5.2-SNAPSHOT I saw this error. And in fact there are more issues with that version, but I am still investigating. This is the first thing I noticed

**Comment by michaelpog** [comment]
But those errors are flooding our logs, and I had not seen them before in prod. There must be a better way to handle this

**Comment by vietj** [comment]
Connection reset by peer are not specific to Vert.x @michaelpog 

what I don't understand if why you are reporting two different stack traces (a short one and a long one) how are they related ?

**Comment by vietj** [comment]
@michaelpog I think they were here before, but we did not print the stack trace before. We changed logging in vertx so now it prints the stack trace and before it was only the message:

https://github.com/eclipse/vert.x/commit/767ca490bffd51caccc17a0b7f502a9565e581c1#diff-0de507733eb75154b7ed71bf07a7ed61

You can avoid them by setting an exception handler on the `HttpConnection` instances and handle them yourself.

**Comment by michaelpog** [comment]
@vietj, sorry for the unorganized and non specific issue report, I should have done  a better job.
I know connection reset by peer is not specific to Vert.x of course.
While testing our application using Vert.x 3.5.2-SNAPSHOT in production, I observed those new Exceptions in the Java flight recorder as well as in the logs.
The first stack trace is from our logs, it floods our logs. I am having trouble understanding how we can suppress this and not have this stack-trace in our logs, even if throwing this exception is a normal behavior.

Then I looked at the Java Flight Recorder and I was trying to capture all the details regarding IOException. So looks like the short one is the exception that ends up in the logs.
The long one.. I'm not sure why I see it, and it's new to me ( comparing to 3.5.0 as far as I know), so maybe it should be a separate issue.

**Comment by manish-panwar** [comment]
In WebClient you can't attach the connection error handlers out of the box - see https://groups.google.com/forum/#!searchin/vertx/connection$20handler%7Csort:date/vertx/W57OyN1goj4/984xzEMGBQAJ

If you were using HttpClient then you can attach the handler.

> httpClientRequest.connectionHandler(conn -> {
>    conn.exceptionHandler(ex -> {
>        // do crazy things.
>    });
> });

Please be aware that Java will throw a generic IOException, so you will have to rely on error message(damn you Java/Oracle) to identify if you want to ignore a specific IO error.

**Comment by michaelpog** [comment]
Oh I see. @manish-panwar  thank you! That is very useful.
So you're saying that other IOExceptions that maybe unrelated and which we WOULD like to log, we will also be caught here. So we have to check the actual message?
That makes sense.

**Comment by manish-panwar** [comment]
Yes!

Actually you should be able to handle it with WebClient as well - try below code.

> webClient.request(method, uriWithQuery)
>                .rxSend()
>              .subscribe(httpResponse -> {
>                    // Handle my response.
>               }, ex -> {
>                   // Handle my error.
>                  if (ex instanceof IOException && StringUtils.contains(ex.getMessage(), "connection reset by peer")) {
>                        // Ignore error
>                    } else {
>                        // Handle error
>                    }
>                });

**Comment by vietj** [comment]
I think by default having a stack trace can be quite scary, I commited this patch https://github.com/eclipse/vert.x/issues/2437 that only log the message like before and log the full trace when debug is on.

**Comment by manish-panwar** [comment]
@vietj - Condition in your code change seems in reverse order than intended. Do you mind checking again?

**Comment by vietj** [comment]
hum right, thanks for checking :-)

**Comment by vietj** [comment]
it's quite complicated to test this kind of things (but not impossible)

**Comment by manish-panwar** [comment]
cool!!!

@michaelpog - My suggestion for WebClient won't work because current version of Vertx will always logs as ERROR if no connection-error-handler was attached.

**Comment by michaelpog** [comment]
And there's no way to set this exceptionHandler in anyway? through WebClient or a wrapped HttpClient?

**Comment by manish-panwar** [comment]
In HttpClient you can always do as suggested in one of my post above. WebClient doesn't provide any handler unless you create your own wrapper around HttpClient as suggested by Julien [here](https://groups.google.com/forum/#!searchin/vertx/connection$20handler%7Csort:date/vertx/W57OyN1goj4/984xzEMGBQAJ)

**Comment by michaelpog** [comment]
Sorry @manish-panwar  if I'm missing something really obviously, but I'm looking at   https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/HttpClient.java and I do not see a way to pass any exception handlers anywhere.
I can see a way to pass a connection handler for an HttpClientRequest created by the HttpClient https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/HttpClientRequest.java#L350
and an exception handler
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/HttpClientRequest.java#L58

But then what is the point of using WebClient if I have to create the HttpClientRequest from the HttpClient?

**Comment by michaelpog** [comment]
I've tested the new version 3.5.2-SNAPSHOT
And I see a lot of those:
```
2018-05-17 12:07:03.188-0700 vert.x-eventloop-thread-6 ERROR Connection reset by peer
2018-05-17 12:07:04.208-0700 vert.x-eventloop-thread-4 ERROR Connection reset by peer
2018-05-17 12:07:20.090-0700 vert.x-eventloop-thread-0 ERROR Connection reset by peer
...
```
In the logs which is fine since I still don't understand how to attach the custom exception handler.

But 
I do see one or two of these:
```
018-05-17 11:56:51.626-0700 vert.x-eventloop-thread-6 ERROR HTTP server connection exception :
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
...
```

still .
Which is weird.
I wonder if there's another place in the code where that exception can be caught and logged with the stack trace.
I see that it is handled though, so it's different from the original stack trace I reported

**Comment by manish-panwar** [comment]
I haven't seen this before. If you don't want Vertx to by default log these as errors, you will have to attach the connection error handler. I think given below code should work for you.

> HttpClientRequest clientRequest = httpClient.post("/");
        clientRequest.connection().exceptionHandler(ex -> {
           if (ex != null && StringUtils.containsIgnoreCase(ex.getMessage(), "Connection reset by peer")) {
               LOGGER.warn("Connection reset by peer.");
           } else {
               LOGGER.error("Some crazy error.", ex);
           }
        });

**Comment by michaelpog** [comment]
@manish-panwar thank you. However this would not work with Web Client at all, there's absolutely no way to attach this exceptionHandler with WebClient in any way I can see.
I think this is something that needs to be fixed.

**Comment by michaelpog** [comment]
@vietj would you mind elaborating on how by wrapping the HTTP client with Webclient I can add this exception handler? 
If it's impossible right now and you don't see any blockers, I can try to find time and work on a pull request for that

**Comment by michaelpog** [comment]
Here is another one that I think is related:
```
2018-05-21 09:36:19.950-0700 vert.x-eventloop-thread-0 WARN An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by michaelpog** [comment]
@vietj  I made a pull request https://github.com/vert-x3/vertx-web/pull/925. Please see review
