### ISSUE TITLE
Issue with OSGi karaf - osgi.wiring.package=io.vertx.ext.auth.impl

### ISSUE THREAD

**Issue by gadieichhorn** [vert-x3/issues#374]
I try to upgrade our vertx vertion from 3.4.2 to 3.5.1

I think I found an issue with the io.vertx.ext.auth.impl package, there is no bundle that exports this package and it is somewhere needed for Karaf to start

> osgi.wiring.package=io.vertx.ext.auth.impl

```
osgi.identity; osgi.identity=vertx-auth-oauth2; type=osgi.bundle; version="[3.5.1,3.5.1]"; resolution:=mandatory [caused by: Unable to resolve vertx-auth-oauth2/3.5.1: missing requirement [vertx-auth-oauth2/3.5.1] osgi.wiring.package; filter:="(osgi.wiring.package=io.vertx.ext.auth.impl)"]]]]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42) ~[?:?]
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:391) ~[?:?]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:377) ~[?:?]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:331) ~[?:?]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:248) ~[?:?]
```

This line seemed to be blocking the export
https://github.com/vert-x3/vertx-auth/blob/9d563d6c65c0be5d8f6c2b598cbdf858b96f3e5e/vertx-auth-common/pom.xml#L80

Was this intentional and how to overcome this issue?

in my Karaf feature.xml

```
        <!--core-->
        <bundle start-level="80">mvn:io.vertx/vertx-core/${vertx.version}</bundle>
        <bundle start-level="80">mvn:com.fasterxml.jackson.core/jackson-core/${jackson.version}</bundle>
        <bundle start-level="80">mvn:com.fasterxml.jackson.core/jackson-databind/${jackson.version}</bundle>
        <bundle start-level="80">mvn:com.fasterxml.jackson.core/jackson-annotations/${jackson.version}</bundle>
        <bundle start-level="80">mvn:org.jetbrains.kotlin/kotlin-osgi-bundle/${kotlin.version}</bundle>

        <!--web-->
        <bundle start-level="80">mvn:io.vertx/vertx-web/${vertx.version}</bundle>
        <bundle start-level="80">mvn:io.vertx/vertx-auth-common/${vertx.version}</bundle>
        <bundle start-level="80">mvn:io.vertx/vertx-bridge-common/${vertx.version}</bundle>
        <bundle start-level="80">mvn:io.vertx/vertx-auth-jwt/${vertx.version}</bundle>
        <bundle start-level="80">mvn:io.vertx/vertx-jwt/${vertx.version}</bundle>
        <bundle start-level="80">mvn:io.vertx/vertx-auth-oauth2/${vertx.version}</bundle>
        <bundle start-level="80">mvn:io.vertx/vertx-auth-htdigest/${vertx.version}</bundle>

```

**Comment by Ngosti2000** [comment]
Were you able to sort this out.. am experiencing the same and there seems to be no response from the vertx team

**Comment by pmlopes** [comment]
With vert.x 4.0.0 OSGi metadata will not be included anymore with the distributed jars.
