### ISSUE TITLE
eventbus  SEVERE: Unhandled exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by z672355589** [vert-x3/issues#394]
2018-07-27 16:38:29,709 [vert.x-eventloop-thread-0] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.vertx.core.net.impl.NetServerImpl$2.handlerAdded() has thrown an exception; removed.
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:616)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:192)
        at io.vertx.core.net.impl.NetServerImpl.connected(NetServerImpl.java:451)
        at io.vertx.core.net.impl.NetServerImpl.access$200(NetServerImpl.java:57)
        at io.vertx.core.net.impl.NetServerImpl$1.initChannel(NetServerImpl.java:209)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:472)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.vertx.core.net.impl.VertxEventLoopGroup.register(VertxEventLoopGroup.java:53)
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: io/netty/channel/VoidChannelPromise
        at io.vertx.core.net.impl.ConnectionBase.<init>(ConnectionBase.java:68)
        at io.vertx.core.net.impl.NetSocketImpl.<init>(NetSocketImpl.java:85)
        at io.vertx.core.net.impl.NetSocketImpl.<init>(NetSocketImpl.java:80)
        at io.vertx.core.net.impl.NetServerImpl.lambda$connected$8(NetServerImpl.java:443)
        at io.vertx.core.net.impl.NetServerImpl$$Lambda$97/667316106.apply(Unknown Source)
        at io.vertx.core.net.impl.VertxNetHandler.handlerAdded(VertxNetHandler.java:39)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        ... 32 common frames omitted
Jul 27, 2018 4:38:29 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
        at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$getServerHandler$10(ClusteredEventBus.java:338)
        at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus$$Lambda$30/159445836.handle(Unknown Source)
        at io.vertx.core.net.impl.NetServerImpl.lambda$connected$11(NetServerImpl.java:457)
        at io.vertx.core.net.impl.NetServerImpl$$Lambda$100/136086165.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl$$Lambda$13/1191044102.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.NetServerImpl.connected(NetServerImpl.java:453)
        at io.vertx.core.net.impl.NetServerImpl.access$200(NetServerImpl.java:57)
        at io.vertx.core.net.impl.NetServerImpl$1.initChannel(NetServerImpl.java:209)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:472)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.vertx.core.net.impl.VertxEventLoopGroup.register(VertxEventLoopGroup.java:53)
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)

**Comment by z672355589** [comment]
version：3.5.2
ClusterManager：zookeeper

**Comment by tsegismont** [comment]
Can you provide a small reproducer ? Thanks

**Comment by z672355589** [comment]
I found nothing exception with version 3.4.2

**Comment by z672355589** [comment]
Let me write a demo。I have a try
