### ISSUE TITLE
There is an error in vert.x and hazelcast,help!!!

### ISSUE THREAD

**Issue by lenovobenben** [vert-x3/issues#398]
Our project uses vert.x(3.3.3) , hazelcast(3.6.3) . Micro-services RPC  appear a bug.

the class file is exist! Why is this happening?

the log:
-------------------------------------------------------------------
2018-08-29 18:23:21.597  WARN  [hz._hzInstance_1_dev.IO.thread-in-0] com.hazelcast.logging.Slf4jFactory$Slf4jLogger.log(Slf4jFactory.java:66) - [localhost]:5706 [dev] [3.6.3] Unhandled exception in hz._hzInstance_1_dev.IO.thread-in-0
java.lang.NoClassDefFoundError: com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader$2
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.destroy(NonBlockingSocketReader.java:247) ~[order-service-1.0-SNAPSHOT-fat.jar:?]
	at com.hazelcast.nio.tcp.TcpIpConnection.close(TcpIpConnection.java:233) ~[order-service-1.0-SNAPSHOT-fat.jar:?]
	at com.hazelcast.nio.tcp.nonblocking.AbstractHandler.onFailure(AbstractHandler.java:85) ~[order-service-1.0-SNAPSHOT-fat.jar:?]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:331) ~[order-service-1.0-SNAPSHOT-fat.jar:?]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:314) ~[order-service-1.0-SNAPSHOT-fat.jar:?]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:234) ~[order-service-1.0-SNAPSHOT-fat.jar:?]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:187) [order-service-1.0-SNAPSHOT-fat.jar:?]
Caused by: java.lang.ClassNotFoundException: com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	... 7 more

**Comment by tsegismont** [comment]
It looks like some classes did not make it to the fat jar.

**Comment by JuKu** [comment]
@lenovobenben It's not the best option, but you can make it work, if you include hazelcast itself:
https://mvnrepository.com/artifact/com.hazelcast/hazelcast/3.10.5

Then he should be able to find this class. Or use an older version of vert.x .

**Comment by lenovobenben** [comment]
@JuKu 
the error happened only once !   Probability is very low. 
I tried to reproduce it ,  but failed.
I have given up.   

Thank You !

**Comment by tsegismont** [comment]
@lenovobenben thanks for letting us know

**Comment by lenovobenben** [comment]
@tsegismont 
The env is Production.
So , I think it is a bug .
very Strange! ! !
