### ISSUE TITLE
Vert.x does not compile with Graal AOT

### ISSUE THREAD

**Issue by codemonstur** [vert-x3/issues#399]
I would like to use the Graal AOT to compile vert.x. I do this:
- create a standard maven project
- add vertx-core 3.5.3 as a dependency
- add a simple main:

    public static void main(final String... args) {
        Vertx.vertx()
            .createHttpServer()
            .requestHandler(request -> request.response().end("Hello, World!\n"))
            .listen(8080);
    }

- use the shader to create a fatjar
- optionally run the jar to prove it works
- install the latest graal and run the native-image command
This error occurs:

Build on Server(pid: 314, port: 39039)
   classlist:   1,939.28 ms
       (cap):     800.08 ms
       setup:   1,147.37 ms
    analysis:   3,717.11 ms
error: Error loading a referenced type: java.util.ServiceConfigurationError: io.vertx.core.spi.VertxFactory: Error reading configuration file
Detailed message:
Error: Error loading a referenced type: java.util.ServiceConfigurationError: io.vertx.core.spi.VertxFactory: Error reading configuration file
Trace: 
        at parsing graaltest.Main.main(Main.java:8)
Call path from entry point to graaltest.Main.main(String[]): 
        at graaltest.Main.main(Main.java:8)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: java.util.ServiceConfigurationError: io.vertx.core.spi.VertxFactory: Error reading configuration file
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.parse(ServiceLoader.java:309)
        at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at io.vertx.core.ServiceHelper.loadFactories(ServiceHelper.java:55)
        at io.vertx.core.ServiceHelper.loadFactories(ServiceHelper.java:42)
        at io.vertx.core.ServiceHelper.loadFactoryOrNull(ServiceHelper.java:32)
        at io.vertx.core.ServiceHelper.loadFactory(ServiceHelper.java:24)
        at io.vertx.core.Vertx.<clinit>(Vertx.java:584)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at jdk.vm.ci.hotspot.HotSpotConstantPool.loadReferencedType(HotSpotConstantPool.java:699)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.loadReferencedType(WrappedConstantPool.java:60)
        at org.graalvm.compiler.java.BytecodeParser.maybeEagerlyResolve(BytecodeParser.java:3971)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.maybeEagerlyResolve(SharedGraphBuilderPhase.java:99)
        at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:3925)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1422)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.genInvokeStatic(SharedGraphBuilderPhase.java:168)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4850)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3135)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2944)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:888)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:782)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:196)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:315)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:502)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/io.vertx.core.spi.VertxFactory not found in /home/jurgen/private/experiments/GraalTest/target/graaltest.jar
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
        at java.net.URL.openStream(URL.java:1045)
        at java.util.ServiceLoader.parse(ServiceLoader.java:304)
        ... 40 more

Error: Processing image build request failed

**Comment by vietj** [comment]
we have people succeeding building native graal images with vertx, can you rather go on the vertx google group to raise your issue and get help ?

**Comment by pmlopes** [comment]
@codemonstur I've created a simple template that can get you started here: https://vertx-starter.jetdrone.xyz/ give it a name and tick the box `native image`.

The generator only works with stable releases so in order to get this working you will need to update the versions of the dependencies from `3.5.3` to `3.6.0-SNAPSHOT` until there are `3.6.x` releases.

Once you have a project skeleton you can build using graal, assuming that graal is your default JVM:

```
export JAVA_HOME=/graal-path
mvn -Pnative-image
```

This will package first your application as a fat jar and then use the `native-image` command to convert it to a native image.

Not all components are known to work so start slowly adding stuff, for example, basic `vertx-web`, `pg-client`, `redis` are known to work, the rest it's a trial and error...

**Comment by codemonstur** [comment]
That starter website is really nice! I looked at the configuration that it generates and I'm both amazed and a little disheartened. Its great to be able to use vert.x but I wonder how long this will remain stable if so many custom settings are needed. 

At the moment though I can't get a driver for a relational db to work with Graal so unless I do a project with only Redis as a backing db I can't really use Graal yet.

**Comment by pmlopes** [comment]
The reactive pg client works without issues with postgres. The flags you see are not really for vertx, if you look closely they are massaging substrate vm to process netty classes properly.
