### ISSUE TITLE
 reply always null when sending from browser (using sockJS) 

### ISSUE THREAD

**Issue by kurt-o-sys** [vert-x3/issues#402]
I'm having issues to make the sockjs eb-bridge to work: the reply I get in the client (browser) is always null. When I send the same message on the eventbus from a verticle without sockJS-bridge, I get the right reply. So it seems the messages are blocked somehow, although I thought that reply messages weren't blocked.

This is some code (from a js verticle):

```
eb.consumer("some.address", function (message) {
  console.log("I have received a message: " + JSON.stringify(message.body()));
  message.reply({"reply": "got it!"});
});
```

The api-verticle:
```
var Vertx = require("vertx-js/vertx");
var Router = require("vertx-web-js/router");
var SockJSHandler = require("vertx-web-js/sock_js_handler");

var server = vertx.createHttpServer();
var router = Router.router(vertx);
var sockJSHandler = SockJSHandler.create(vertx, {"heartbeatInterval": 2000});
<...>

var allowEvents = [{"addressRegex": "some\\..+"}];
sockJSHandler.bridge({"inboundPermitteds": allowEvents,
                      "outboundPermitteds": allowEvents});

router.route("/eb/*").handler(sockJSHandler.handle);
<...>
server.requestHandler(router.accept).listen(config.port);

console.log("REST server started at port: " + config.port)
```

index.html:

```
<html>

<head>
  <script src="http://cdn.jsdelivr.net/sockjs/0.3.4/sockjs.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vertx/3.5.3/vertx-eventbus.min.js"></script>

  <script>

    var eb = new EventBus('http://localhost:8085/eb');
    var myId = "my-id";

    eb.onopen = function() {
      console.log('opened event bus...');
      eb.registerHandler('some.' + myId, function(err, message) {
        console.log('received error: ' + JSON.stringify(err));
        console.log('received message: ' + JSON.stringify(message));
      });

      eb.send('some.address', {"some": "event"},
        function(reply) {
          console.log(reply);
        });
    };
  </script>
</head>

<body>
  <...>
</body>

</html>
```
code that does work, without sockJS-bridge (from a Java-verticle):
```
      eb.send("some.address", new JsonObject().put("some", "event"), reply -> {
        if (reply.succeeded()) {
          System.out.println("Received reply " + reply.result().body());
        } else {
          System.out.println("No reply: timed out");
        }
      })
```

Probably related to the issue: when I follow the example from the docs and add a event bus bridge event handler, I get an error. From https://vertx.io/docs/vertx-web/js/#_sockjs :

```
sockJSHandler.bridge({"inboundPermitteds": allowEvents,
                      "outboundPermitteds": allowEvents},
                     function(evt) {
                       console.log("event bus event: " + JSON.stringify(evt));
                       evt.complete(true);
                     });
```

the `evt` seems to be an empty object `{}`:

```
event bus event: {}
Sep 14, 2018 11:57:23 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.NullPointerException
        at io.vertx.ext.web.handler.sockjs.impl.EventBusBridgeImpl.lambda$checkCallHook$3(EventBusBridgeImpl.java:168)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.ext.web.handler.sockjs.impl.EventBusBridgeImpl.checkCallHook(EventBusBridgeImpl.java:166)
        <...>
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$895$\^eval\_#88\!17\^eval\_.L:1#SockJSHandler#handle(vertx-web-js/sock_js_handler.js:53)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$891$5507A$\^eval\_#88\!17\^eval\_.L:1#Route#handler#L:156(vertx-web-js/route.js:157)
        at jdk.nashorn.javaadapters.io_vertx_core_Handler.handle(Unknown Source)
        <...>
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$885$\^eval\_#88\!17\^eval\_.L:1#Router#accept(vertx-web-js/router.js:48)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$883$2887A$\^eval\_#88\!17\^eval\_.L:1#HttpServer#requestHandler#L:83(vertx-js/http_server.js:84)
        at jdk.nashorn.javaadapters.io_vertx_core_Handler.handle(Unknown Source)
        <...>
```

**Comment by kurt-o-sys** [comment]
ok, solved the first problem: the callback takes 2 args: first one is error, second one is reply... it would be good to update the docs.
