### ISSUE TITLE
java11 Unsafe

### ISSUE THREAD

**Issue by yiming33** [vert-x3/issues#419]
udpate java8 to java11

java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:259)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.vertx.core.net.impl.transport.Transport.eventLoopGroup(Transport.java:132)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:146)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:30)
	at io.vertx.core.Vertx.vertx(Vertx.java:75)
	at com.hydsoft.student.handler.impl.StudentHandlerImpl.main(StudentHandlerImpl.java:68)
15:08:10.296 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: unavailable true
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:273)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:266)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:259)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.vertx.core.net.impl.transport.Transport.eventLoopGroup(Transport.java:132)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:146)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:30)
	at io.vertx.core.Vertx.vertx(Vertx.java:75)
	at com.hydsoft.student.handler.impl.StudentHandlerImpl.main(StudentHandlerImpl.java:68)
15:08:10.298 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @5b8dfcc1
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:315)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:306)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:259)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.vertx.core.net.impl.transport.Transport.eventLoopGroup(Transport.java:132)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:146)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:30)
	at io.vertx.core.Vertx.vertx(Vertx.java:75)
	at com.hydsoft.student.handler.impl.StudentHandlerImpl.main(StudentHandlerImpl.java:68)

![image](https://user-images.githubusercontent.com/19584310/48396686-44117a80-e756-11e8-8360-7c23e0e85d54.png)

**Comment by vietj** [comment]
which version of Vert.x ?

**Comment by jponge** [comment]
Can you also show us some of the code you wrote @yiming33?

**Comment by yiming33** [comment]
> which version of Vert.x ?
3.5.3

**Comment by yiming33** [comment]
> Can you also show us some of the code you wrote @yiming33?

Just new vertx in main method
New vertx    throws an exception

**Comment by yiming33** [comment]
Now I roll back the Java version to 8,everything is back to normal.

**Comment by tunovic** [comment]
Have related exception as DEBUG:
```
[INFO] 20:02:55.423 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
[INFO] java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @6a6afff2
[INFO] 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
[INFO] 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
[INFO] 	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334)
[INFO] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:325)
[INFO] 	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:212)
[INFO] 	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:80)
[INFO] 	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:268)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
[INFO] 	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
[INFO] 	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:134)
[INFO] 	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
[INFO] 	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
[INFO] 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
[INFO] 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
[INFO] 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
[INFO] 	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
[INFO] 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
[INFO] 	at io.netty.channel.nio.NioEventLoopGroup
[INFO] .<init>(NioEventLoopGroup.java:72)
[INFO] 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
[INFO] 	at io.vertx.core.net.impl.transport.Transport.eventLoopGroup(Transport.java:132)
[INFO] 	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:146)
[INFO] 	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
[INFO] 	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
[INFO] 	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:30)
[INFO] 	at io.vertx.core.Vertx.vertx(Vertx.java:75)
[INFO] 	at com.myapp.service.Application.main(Application.kt:14)
```
Vert.x 3.6.2 with Java 11. Has this to do with Netty Java 11 support?

**Comment by vietj** [comment]
have you checked Netty issue tracker if that's reported as well ?

**Comment by jhult** [comment]
See https://github.com/netty/netty/issues/7817 for more info.
