### ISSUE TITLE
Unnamed module reads package io.vertx.reactivex from both vertx.rx.java2 and vertx.rx.java2.gen

### ISSUE THREAD

**Issue by Falx** [vert-x3/issues#431]
Making a basic project with vertx 3.6.0 where rxjava2 is used, I get the next errors:
Error:java: the unnamed module reads package io.vertx.reactivex from both vertx.rx.java2 and vertx.rx.java2.gen

Is there still a split package then? This blocks modularization of our vertx based applications.

**Comment by vietj** [comment]
can you try excluding `vertx.rx.java2.gen` ?

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-rx/issues/168

**Comment by Falx** [comment]
How do you mean? In the pom.xml?
Because there I only have this:

```xml
  <dependencies>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-config</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-stack-depchain</artifactId>
                <version>${vertx.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by vietj** [comment]
use a Maven exclusion on 

```
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java2</artifactId>
        </dependency>
```

**Comment by Falx** [comment]
That gets me further, thanks.
But then when I want to use the `io.reactivex.rxjava2/rxjava` dependency (to get acces to the  Single class). I get the next error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/vertx/lang/rx/TypeArg
	at vertx.rx.java2@3.6.0/io.vertx.reactivex.core.Vertx.<clinit>(Vertx.java:90)
	at tester.jdk11/technology.idlab.tester.main.Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: io.vertx.lang.rx.TypeArg
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```

**Comment by vietj** [comment]
can you make sure that all your modules have been updated ?

it seems that your Vertx version is not 3.6.0

**Comment by vietj** [comment]
actually it seems that you need

vertx-rx-gen in your path

so you need to add it back because it was excluded by the exclusion

can you do that and report ?

**Comment by Falx** [comment]
Ok, nice, for now adding in vertx-rx-gen seems to fix it.

```xml
 <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-rx-gen</artifactId>
    <version>${vertx.version}</
</dependency>
```
So this should be fixed in 4.0.0 then? Or earlier?

**Comment by vietj** [comment]
we will try to fix this for 3.6.1

**Comment by vietj** [comment]
thanks for reporting
