### ISSUE TITLE
Micrometer exception

### ISSUE THREAD

**Issue by neterium-dev** [vert-x3/issues#464]
Hi, 

when my vertx cluster starts, I sometimes have this exception if I want to directly send a message. It does not happen afterwards. The issue is that the exception is raised in the beginHandleMessage, so the handle itself is not called.

Here's the stack trace:

```
java.lang.NullPointerException: null
	at io.vertx.micrometer.impl.VertxEventBusMetrics.beginHandleMessage(VertxEventBusMetrics.java:90)
	at io.vertx.micrometer.impl.VertxEventBusMetrics.beginHandleMessage(VertxEventBusMetrics.java:33)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:262)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:242)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Maybe that, in VertxEventBusMetrics::beginHandleMessage, you should check if handler is null first? Looks like it's possible during a very short time frame after the eventbus is initialized...

Thomas

**Comment by tsegismont** [comment]
Can you please report this in the vertx-micrometer-metrics repo? Thank you!

**Comment by neterium-dev** [comment]
Sorry for submitting in the wrong place.
Here's the link: 
[(https://github.com/vert-x3/vertx-micrometer-metrics/issues/78)]

**Comment by tsegismont** [comment]
@neterium no worries. Thanks again.
