### ISSUE TITLE
BlockedThreadChecker.log not work in 4.0.0-x, but 3.x is work ok.

### ISSUE THREAD

**Issue by takeseem** [vert-x3/issues#523]
### Questions

#522 had be close and I can't to reopen, I have to create this.

First thanks for your answer,  and hear 4.0 will released a few months :)
I will continue in Vertx 4 work.

- `BlockedThreadChecker.log` not work in **4.0.0-milestone4** and **4.0.0-SNAPSHOT**, but 3.9.0 is work ok. 
I create a **demo project,** this test code is https://github.com/takeseem/takeseem-demo-vertx/blob/master/src/main/java/com/takeseem/demo/vertx/issues/VertxIssues522.java#L47

log4j2 2.13.1,  includeLocation="true"
in eclipse debug: [StackLocator.calcLocation(StackLocator.java:79)](https://github.com/apache/logging-log4j2/blob/log4j-2.13.1/log4j-api/src/main/java/org/apache/logging/log4j/util/StackLocator.java#L79), but I found in fact it's [logging-log4j2-java9 StackLocator.java:79](https://github.com/apache/logging-log4j2/blob/log4j-2.13.1/log4j-api-java9/src/main/java/org/apache/logging/log4j/util/StackLocator.java#L79), but in my classpath I can't found the log4j-api-java9.jar?
```
Exception in thread "vertx-blocked-thread-checker" java.lang.NullPointerException
	at org.apache.logging.log4j.util.StackLocator.calcLocation(StackLocator.java:79)
	at org.apache.logging.log4j.util.StackLocatorUtil.calcLocation(StackLocatorUtil.java:78)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:153)
	at org.apache.logging.slf4j.Log4jLogger.log(Log4jLogger.java:376)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:188)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:160)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:156)
	at io.vertx.core.logging.SLF4JLogDelegate.warn(SLF4JLogDelegate.java:86)
	at io.vertx.core.impl.logging.LoggerAdapter.warn(LoggerAdapter.java:79)
	at io.vertx.core.impl.BlockedThreadChecker$1.run(BlockedThreadChecker.java:59)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

### Version

- 4.0.0-milestone4
- 4.0.0-SNAPSHOT

### Extra
* Ubuntu 18.04.4 LTS
* OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by vietj** [comment]
thanks I will have a look at the reproducer

**Comment by vietj** [comment]
in this project the class `StackLocator` is in the log4j-api 2.13.1 jar

**Comment by vietj** [comment]
this class is present using multi release jar feature:

```
MBP-de-julien:2.13.1 julien$ jar -tvf log4j-api-2.13.1.jar | grep StackLocator
  5612 Tue Feb 25 19:52:58 CET 2020 org/apache/logging/log4j/util/StackLocator.class
  1894 Tue Feb 25 19:52:54 CET 2020 META-INF/versions/9/org/apache/logging/log4j/util/StackLocator$FqcnCallerLocator.class
  2553 Tue Feb 25 19:53:00 CET 2020 org/apache/logging/log4j/util/StackLocatorUtil.class
  7373 Tue Feb 25 19:52:54 CET 2020 META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class
```

**Comment by vietj** [comment]
it is a bug in log4j : https://issues.apache.org/jira/browse/LOG4J2-2809

**Comment by vietj** [comment]
there is no release with this fix yet.
