### ISSUE TITLE
VertxNetServerMetrics connected NullPointerException

### ISSUE THREAD

**Issue by hjx27000cs** [vert-x3/issues#550]
堆栈：
java.lang.NullPointerException: null
	at io.vertx.micrometer.impl.VertxNetServerMetrics$Instance.connected(VertxNetServerMetrics.java:65) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.micrometer.impl.VertxNetServerMetrics$Instance.connected(VertxNetServerMetrics.java:56) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpServerChannelInitializer.lambda$configureHttp1$4(HttpServerChannelInitializer.java:258) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[punk_gate-jar-with-dependencies.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [punk_gate-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[ERROR] [2020-05-20 17:20:07] [vert.x-worker-thread-4] com.yandao.game.core.verticle.MainVerticle.lambda$rxStart$0(MainVerticle.java:40): handler
java.util.NoSuchElementException: handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1085) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpHandlers.initializeWebsocketExtensions(HttpHandlers.java:92) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpHandlers.handle(HttpHandlers.java:69) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpHandlers.handle(HttpHandlers.java:34) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35) ~[punk_gate-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[punk_gate-jar-with-dependencies.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [punk_gate-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

不知道怎么重现，但是有时候就会来一次。

**Comment by vietj** [comment]
do you have a reproducer ?

**Comment by hjx27000cs** [comment]
> do you have a reproducer ?
没有

**Comment by hjx27000cs** [comment]
The recent upgrade to 3.9.2 is still an occasional occurrence.

Is there any way to fix this problem, because this bug will directly card the main thread

**Comment by KirillMoskvin** [comment]
Just run into the same issue on 3.8.3, is there any updates on this?

**Comment by vietj** [comment]
do you have a way to reproduce it @KirillMoskvin ?
