### ISSUE TITLE
Vertx 3.9.5 tries to connect failed node 

### ISSUE THREAD

**Issue by oleg-kiriyenko** [vert-x3/issues#573]
### Questions

After node fails vertx still tries to connect (send message) to the failed node.

### Version

3.9.5 on Windows 2012R2

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

No. Only log of vertx and hazlecast.

### Steps to reproduce

1. Start vertx cluster
2. Disconnect one node
3. Send request to the active node. It will send it to the failed node and will get timeout exception.
4. 
### Extra

We have two nodes 192.168.8.210 and 192.168.8.215. After 192.168.8.215 fails (stopped) Vertx still tries to send request to it.

```
Members {size:2, ver:2} [
	Member [192.168.8.210]:5701 - 4cbe3290-c785-402f-b87e-59299a12fa3a this
	Member [192.168.8.215]:5701 - ef64585b-f523-49fe-b23c-2089b0693e7f
]

.....After node failes

2021-01-21 16:56:31.835  INFO 2844 --- [cached.thread-4] c.h.internal.cluster.ClusterService      : [192.168.8.210]:5701 [CLUSTER_TITAN2] [3.12.2] 

Members {size:1, ver:3} [
	Member [192.168.8.210]:5701 - 4cbe3290-c785-402f-b87e-59299a12fa3a this
]

2021-01-21 16:56:31.837  INFO 2844 --- [ITAN2.migration] c.h.i.partition.impl.MigrationManager    : [192.168.8.210]:5701 [CLUSTER_TITAN2] [3.12.2] Partition balance is ok, no need to re-partition cluster data... 
2021-01-21 16:56:31.841  INFO 2844 --- [cached.thread-8] c.h.t.TransactionManagerService          : [192.168.8.210]:5701 [CLUSTER_TITAN2] [3.12.2] Committing/rolling-back live transactions of [192.168.8.215]:5701, UUID: ef64585b-f523-49fe-b23c-2089b0693e7f
2021-01-21 16:56:36.838  INFO 2844 --- [tloop-thread-13] c.n.p.l.cluster.ClusterLeaderSelector    : Lock and select master
2021-01-21 16:56:36.839  INFO 2844 --- [tloop-thread-13] c.n.p.l.cluster.ClusterLeaderSelector    : Accepted lock
2021-01-21 16:56:36.839  WARN 2844 --- [tloop-thread-13] c.n.p.l.cluster.ClusterLeaderSelector    : Quorum is not used. But it is highly recommended. Please add quorum tests!
2021-01-21 16:56:36.841  INFO 2844 --- [tloop-thread-13] c.n.p.l.cluster.ClusterLeaderSelector    : We are already master node!
2021-01-21 16:56:36.841  INFO 2844 --- [tloop-thread-13] c.n.p.l.cluster.ClusterLeaderSelector    : Cluster lock released
2021-01-21 16:56:44.603  WARN 2844 --- [ntloop-thread-7] i.v.c.e.impl.clustered.ConnectionHolder  : Connecting to server 192.168.8.215:5600 failed

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.8.215:5600
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_202-release]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_202-release]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202-release]

2021-01-21 16:57:25.322  WARN 2844 --- [ntloop-thread-7] i.v.c.e.impl.clustered.ConnectionHolder  : Connecting to server 192.168.8.215:5600 failed

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.8.215:5600
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_202-release]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_202-release]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202-release]
```

**Comment by tsegismont** [comment]
Can you please open this issue in `vertx-hazelcast` ? Thank you.

Also, we'd need some basic information in order to reproduce: snippets, how the application is packaged/started/stopped.

**Comment by oleg-kiriyenko** [comment]
https://github.com/vert-x3/issues/issues/573#issuecomment-764716939

I managed to reproduce an issue in small project if I add my own node listener to the cluster manager.
I need it because I have some complex logic of cluster leader selection and standard HAManager doesn't fit my needs.
How is it possible to overcome an issue? To have own cluster node listener for application needs.

```java
package com.example.starter;

import com.hazelcast.config.Config;
import com.hazelcast.config.InterfacesConfig;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.eventbus.EventBusOptions;
import io.vertx.core.json.JsonObject;
import io.vertx.core.spi.cluster.ClusterManager;
import io.vertx.core.spi.cluster.NodeListener;
import io.vertx.spi.cluster.hazelcast.ConfigUtil;
import io.vertx.spi.cluster.hazelcast.HazelcastClusterManager;

public class Main {

  public static void main(String[] args) {

    final String host = args[0];
    final String name = args[1];
    final int port = Integer.valueOf(args[2]);

    final Config hazelcastConfig = ConfigUtil.loadConfig();
    hazelcastConfig.getGroupConfig().setName("TestCluster").setPassword("TestPassword");

    final InterfacesConfig ifaceConfig = new InterfacesConfig();
    ifaceConfig.setEnabled(true).addInterface(host);
    hazelcastConfig.getNetworkConfig().setInterfaces(ifaceConfig);

    final ClusterManager mgr = new HazelcastClusterManager(hazelcastConfig);


    final EventBusOptions eventBusOptions = new EventBusOptions()
            .setClustered(true)
            .setHost(host);

    final VertxOptions options = new VertxOptions()
            .setClusterManager(mgr)
            .setEventBusOptions(eventBusOptions);

    Vertx.clusteredVertx(options, res -> {
      if (res.succeeded()) {
        final Vertx vertx = res.result();
        //Add listener
        mgr.nodeListener(new NodeListener() {
          @Override
          public void nodeAdded(String nodeID) {
            System.out.println("Node added");
          }

          @Override
          public void nodeLeft(String nodeID) {
            System.out.println("Node removed");
          }
        });
        //Test service
        final DeploymentOptions testOptions = new DeploymentOptions()
          .setConfig(new JsonObject().put("name", name))
          .setWorker(true);
        vertx.deployVerticle("com.example.starter.TestServiceVerticle", testOptions);
        //Http
        final DeploymentOptions httpOptions = new DeploymentOptions()
          .setConfig(new JsonObject().put("port", port))
          .setInstances(4);
        vertx.deployVerticle("com.example.starter.HttpVerticle", httpOptions);
      } else {
        // failed!
      }
    });
  }

}

```

**Comment by tsegismont** [comment]
Indeed, you shouldn't replace the Vert.x node listener.

You could create a Hazelcast instance from your config and register your own membership listener.

**Comment by oleg-kiriyenko** [comment]
I solved a problem with the hack. Is it possible to add API addNodeListener/removeNodeListener

My hack is. It could be used to extend API.

```java
public class ExtHazelcastClusterManager extends HazelcastClusterManager {

    private final List<NodeListener> listeners;

    public ExtHazelcastClusterManager(Config conf) {
        super(conf);
        this.listeners = new ArrayList<>();
        super.nodeListener(new NodeListener() {
            @Override
            public void nodeAdded(String nodeID) {
                listeners.forEach(lst -> lst.nodeAdded(nodeID));
            }
            @Override
            public void nodeLeft(String nodeID) {
                listeners.forEach(lst -> lst.nodeLeft(nodeID));
            }
        });
    }

    @Override
    public void nodeListener(NodeListener listener) {
        listeners.add(listener);
    }

}
```
