### ISSUE TITLE
Error running java verticle from source (e.g. vertx run Server.java)

### ISSUE THREAD

**Issue by nevenr** [vert-x3/issues#79]
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo>%JAVA_HOME%\bin\java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo>vertx -version
3.2.0
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo>vertx run Server.java
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:20: error: illegal start of expression
    vertx.createNetServer().connectHandler(sock -> {
                                                 ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:20: error: illegal start of expression
    vertx.createNetServer().connectHandler(sock -> {
                                                   ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:20: error: ';' expected
    vertx.createNetServer().connectHandler(sock -> {
                                                    ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:23: error: illegal start of expression
      Pump.pump(sock, sock).start();
          ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:23: error: ';' expected
      Pump.pump(sock, sock).start();
               ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:23: error: not a statement
      Pump.pump(sock, sock).start();
                ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:23: error: ';' expected
      Pump.pump(sock, sock).start();
                    ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:23: error: not a statement
      Pump.pump(sock, sock).start();
                      ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:23: error: ';' expected
      Pump.pump(sock, sock).start();
                          ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:25: error: illegal start of type
    }).listen(1234);
     ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:25: error: ';' expected
    }).listen(1234);
      ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:25: error: invalid method declaration; return type required
    }).listen(1234);
       ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:25: error: illegal start of type
    }).listen(1234);
              ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:27: error: <identifier> expected
    System.out.println("Echo server is now listening");
                      ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:27: error: illegal start of type
    System.out.println("Echo server is now listening");
                       ^
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo\Server.java:30: error: class, interface, or enum expected
}
^
java.lang.RuntimeException: Compilation failed
        at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:120)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:38)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
        at io.vertx.core.Launcher.main(Launcher.java:48)
Caused by: java.lang.RuntimeException: Compilation failed!
        at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:117)
        ... 21 more
Failed in deploying verticle
java.lang.RuntimeException: Compilation failed
        at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:120)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:38)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
        at io.vertx.core.Launcher.main(Launcher.java:48)
Caused by: java.lang.RuntimeException: Compilation failed!
        at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:117)
        ... 21 more

java.lang.RuntimeException: Compilation failed
        at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:120)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:38)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
        at io.vertx.core.Launcher.main(Launcher.java:48)
Caused by: java.lang.RuntimeException: Compilation failed!
        at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:117)
        ... 21 more
C:\Workspaces\vertx-examples\core-examples\src\main\java\io\vertx\example\core\net\echo>
```

**Comment by nevenr** [comment]
The same thing with Linux
```
nevenr@mustang ~/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo $ vertx run Server.java 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:20: error: illegal start of expression
    vertx.createNetServer().connectHandler(sock -> {
                                                 ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:20: error: illegal start of expression
    vertx.createNetServer().connectHandler(sock -> {
                                                   ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:20: error: ';' expected
    vertx.createNetServer().connectHandler(sock -> {
                                                    ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:23: error: illegal start of expression
      Pump.pump(sock, sock).start();
          ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:23: error: ';' expected
      Pump.pump(sock, sock).start();
               ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:23: error: not a statement
      Pump.pump(sock, sock).start();
                ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:23: error: ';' expected
      Pump.pump(sock, sock).start();
                    ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:23: error: not a statement
      Pump.pump(sock, sock).start();
                      ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:23: error: ';' expected
      Pump.pump(sock, sock).start();
                          ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:25: error: illegal start of type
    }).listen(1234);
     ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:25: error: ';' expected
    }).listen(1234);
      ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:25: error: invalid method declaration; return type required
    }).listen(1234);
       ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:25: error: illegal start of type
    }).listen(1234);
              ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:27: error: <identifier> expected
    System.out.println("Echo server is now listening");
                      ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:27: error: illegal start of type
    System.out.println("Echo server is now listening");
                       ^ 
/home/nevenr/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo/Server.java:30: error: class, interface, or enum expected
}
^ 
java.lang.RuntimeException: Compilation failed
	at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:120)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:38)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
	at io.vertx.core.Launcher.main(Launcher.java:48)
Caused by: java.lang.RuntimeException: Compilation failed!
	at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:117)
	... 21 more
Failed in deploying verticle 
java.lang.RuntimeException: Compilation failed
	at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:120)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:38)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
	at io.vertx.core.Launcher.main(Launcher.java:48)
Caused by: java.lang.RuntimeException: Compilation failed!
	at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:117)
	... 21 more

java.lang.RuntimeException: Compilation failed
	at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:120)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:38)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
	at io.vertx.core.Launcher.main(Launcher.java:48)
Caused by: java.lang.RuntimeException: Compilation failed!
	at io.vertx.core.impl.verticle.CompilingClassLoader.<init>(CompilingClassLoader.java:117)
	... 21 more
nevenr@mustang ~/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo $ $JAVA_HOME/bin/java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
nevenr@mustang ~/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo $ vertx -version
3.2.0 
nevenr@mustang ~/workspace/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo $ 

```

**Comment by cescoffier** [comment]
Hi,

Can you check if you don't have a JAVA_HOME env variable set ? If so, vertx is using this JVM.

**Comment by nevenr** [comment]
Hi,
Yes I have and that's why I checked java version in previous messages like this:
windows:
```
%JAVA_HOME%\bin\java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)
```
linux:
```
$JAVA_HOME/bin/java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

Regards,
N.

**Comment by cescoffier** [comment]
I confirmed the bug (I've reproduced it).

**Comment by cescoffier** [comment]
After a quite long investigation, it comes from Ceylon overriding an internal class provided by the JRE and used by the internal compiler (`com.sun.tools.javac.code.Source`).

**Comment by cescoffier** [comment]
As a quick and dirty work around, remove `vertx-lang-ceylon-*.jar` and `ceylon-complete-1.2.0.jar` from `$VERTX_HOME/lib`

**Comment by cescoffier** [comment]
An issue has been opened on the Ceylon issue tracker: https://github.com/ceylon/ceylon/issues/5881

**Comment by cescoffier** [comment]
@vietj any update ?

**Comment by vietj** [comment]
no, @FroMage and/or @quintesse know better than me :-)

**Comment by quintesse** [comment]
ceylon/ceylon#5881 has been closed as fixed, we're now in the process of creating a new Ceylon release.

**Comment by vietj** [comment]
thanks, do you have an ETA for the release ?

**Comment by quintesse** [comment]
I see 12 open issues on that version so I'd say: Real Soon Now :tm:

**Comment by vietj** [comment]
thanks, let us know when it is available.

**Comment by cescoffier** [comment]
For the time being, we drop ceylon from the stacks (full and min). It will be re-added as soon as the ceylon release is out.

**Comment by cescoffier** [comment]
So, the issue has been resolved in https://github.com/vert-x3/vertx-stack/issues/40. Ceylon is not included by default anymore (we discussed with the Ceylon team about this decision). Instructions to include ceylon are provided in the vertx-stack.json file.

I consider this issue fixed now.

**Comment by nevenr** [comment]
Hey,

This is what I've just read and it's something really new and interesting, you can read more at <http://shyputhado.networktask.com/xyzfn>

Yours, nevenr@mail.com

**Comment by nevenr** [comment]
Hey,

Can you help me get everything ready for the party? Look at my to do list, i need your help! Here is the list  <http://sikacredi.terriholdren.com/xyjhqg>

nevenr@mail.com

**Comment by nevenr** [comment]
Hi, I was looking for some stuff on the web and found this, you're gonna like it, just take a look here <http://shuvobaje.tishrobinson.net/xyocdsbi>

nevenr@mail.com

**Comment by nevenr** [comment]
Hey,

I've suddenly  came across an interesting article,  it's amazing! please read it  here and tell me what you think  <http://effect.cci-patents.com/e4qzuw>

Warm regards, nevenr@mail.com

**Comment by nevenr** [comment]
Hi,
I've read about some  cool things recently and I though you might  be inerested  too, here is the link <http://describe.stansburyparkonline.net/e4jxzmwx>

nevenr@mail.com
