### ISSUE TITLE
unerscore in request param name

### ISSUE THREAD

**Issue by alex-inqwise** [vert-x3/issues#88]
When part of request parameter is underscore (like "account_id"). Example:
router.post("/:account_id").handler(this::get);

Received the following exception:

java.util.concurrent.CompletionException: java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 11
/(?<account_id>[^/]+)
           ^
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) ~[?:1.8.0_20]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) ~[?:1.8.0_20]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_20]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) ~[?:1.8.0_20]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) ~[?:1.8.0_20]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) ~[?:1.8.0_20]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_20]
Caused by: java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 11
/(?<account_id>[^/]+)
           ^
	at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_20]
	at java.util.regex.Pattern.groupname(Pattern.java:2799) ~[?:1.8.0_20]
	at java.util.regex.Pattern.group0(Pattern.java:2844) ~[?:1.8.0_20]
	at java.util.regex.Pattern.sequence(Pattern.java:2051) ~[?:1.8.0_20]
	at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_20]
	at java.util.regex.Pattern.compile(Pattern.java:1696) ~[?:1.8.0_20]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_20]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_20]
	at io.vertx.ext.web.impl.RouteImpl.createPatternRegex(RouteImpl.java:427) ~[vertx-web-3.2.0.jar:?]
	at io.vertx.ext.web.impl.RouteImpl.setPath(RouteImpl.java:395) ~[vertx-web-3.2.0.jar:?]
	at io.vertx.ext.web.impl.RouteImpl.<init>(RouteImpl.java:74) ~[vertx-web-3.2.0.jar:?]
	at io.vertx.ext.web.impl.RouterImpl.route(RouterImpl.java:89) ~[vertx-web-3.2.0.jar:?]
	at io.vertx.ext.web.impl.RouterImpl.post(RouterImpl.java:174) ~[vertx-web-3.2.0.jar:?]

**Comment by pmlopes** [comment]
this should be reported on https://github.com/vert-x3/vertx-web/issues

**Comment by alex-inqwise** [comment]
create ?

**Comment by pmlopes** [comment]
This is a vertx-web issue not a core issue so it should be created there. I've created a new issue and it will be tracked there.

**Comment by alex-inqwise** [comment]
Thanks Paulo!
