### ISSUE TITLE
Netty rejects undeployment tasks when closing Vert.x

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#9]
because the Netty event loop should be closed after all undeployments are processed.

````
Running io.vertx.example.unit.test.MyJUnitTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.625 sec
Apr 14, 2015 10:10:57 AM io.netty.channel.AbstractChannel$AbstractUnsafe invokeLater
WARNING: Can't invoke task later as EventLoop rejected it
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:725)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.invokeLater(AbstractChannel.java:779)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:612)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:581)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1098)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543)
	at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:533)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by purplefox** [comment]
Do you have a test that reproduces this?

**Comment by vietj** [comment]
you can reproduce it the vertx-examples with vertx-unit io.vertx.example.unit.test.MyJUnitTest

**Comment by vietj** [comment]
I sent an email on vertx-dev https://groups.google.com/forum/#!topic/vertx-dev/k-KOzpCbvkU

**Comment by purplefox** [comment]
Can this be closed now?

**Comment by vietj** [comment]
sure +1
