### ISSUE TITLE
Vertx + Shade + Spaces in Path = FileResolver FileNotFoundException (with stack trace & SSCCE)

### ISSUE THREAD

**Issue by jasonCodesAway** [vert-x3/issues#91]
1. Create a Vertx HttpServer
2. Add a Router and route with a default StaticHandler (code below)
3. Use the maven shade plugin to generate a fat jar for the project
4. Run that jar from any path with spaces in it
5. Point your browser to http://localhost:8082/
and then:
```
Feb 03, 2016 8:03:58 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.io.FileNotFoundException: C:\temp\Hello%20Space\Shaded.jar (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at io.vertx.core.impl.FileResolver.toZipInputStream(FileResolver.java:171)
        at io.vertx.core.impl.FileResolver.unpackFromJarURL(FileResolver.java:180)
        at io.vertx.core.impl.FileResolver.resolveFile(FileResolver.java:121)
        at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:657)
        at io.vertx.core.file.impl.FileSystemImpl$6.perform(FileSystemImpl.java:517)
        at io.vertx.core.file.impl.FileSystemImpl$6.perform(FileSystemImpl.java:514)
        at io.vertx.core.file.impl.FileSystemImpl.propsBlocking(FileSystemImpl.java:150)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$getFileProps$4(StaticHandlerImpl.java:264)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:233)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:264)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendStatic(StaticHandlerImpl.java:184)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.handle(StaticHandlerImpl.java:141)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.handle(StaticHandlerImpl.java:51)
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
        at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
        at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:274)
        at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:392)
        at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:134)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$25(HttpServerImpl.java:537)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:535)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:469)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:420)
        at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:85)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Unknown Source)
```

- OS: Windows 7 64-bit
- JDK: 1.8_72
- vertx version: 3.2.0
- maven-shade-plugin version: 2.4.3

I'm putting a full maven SSCCE [here](https://drive.google.com/file/d/0BxnW_9WhyR1MdnA3OGRyaG8tZVU/view?usp=sharing). This links to a zip file that contains:

-  the pre-built shaded jar
- all source code and the maven project
- a batch and script to rebuild the shaded jar if you like
- sample console output of the code working (if deployed in a directory without spaces) and sample console output of the code working (if deployed in a directory with spaces)

If that link isn't working the relevant code is below.

```
    public static void main(String[] args) {
        final int serverPort = 8082;
        final Vertx vertx = Vertx.vertx();
        final HttpServer server = vertx.createHttpServer();

        // Serve up client UI content (i.e. html, javascript, css, etc.). This will serve up everything in 
        final Router router = Router.router(vertx);
        router.route("/*").handler(StaticHandler.create());
        server.requestHandler(router::accept).listen(serverPort);
        logger.info("Server listening on port {}", serverPort);
    }
```
and relevant portions of the POM:
```
    <dependencies>
        <!-- HTTPServer and EventBus functionality -->
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
            <version>3.2.0</version>
        </dependency>
        <!-- Logging-->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.13</version>
        </dependency>
        <!-- Logging-->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.3</version>
        </dependency>
    </dependencies>
    <profiles>
        <!-- Creates a single jar that allows execution of the Server. This is triggered by this build command: 'mvn -Drelease install'-->
        <profile>
            <activation>
                <property>
                    <name>release</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>2.4.3</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <transformers>
                                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                            <manifestEntries>
                                                <Main-Class>vertxspacedout.Main</Main-Class>
                                            </manifestEntries>
                                        </transformer>
                                    </transformers>
                                    <artifactSet/>
                                    <outputFile>${project.build.directory}/Shaded.jar</outputFile>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>            
        </profile>
    </profiles>
```

**Comment by cescoffier** [comment]
Fixed in I think it’s was fixed in https://github.com/eclipse/vert.x/pull/1263.

Could you try with the snapshot version ?

**Comment by jasonCodesAway** [comment]
It works with 3.3.0-SNAPSHOT! :+1: I'll update to the next stable release when it gets cut. Thank you!!
